# Generated by Django 6.1.1 on 2026-09-04 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.business'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['business', 'is_active'], name='accounts_ac_busines_0f5978_idx'),
        ),
    ]
